// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizlGTlhVGZZw3-AGQLYVoADs8KzcK5FA',
    appId: '1:897401434851:web:836ee4ef602c181f57cbd6',
    messagingSenderId: '897401434851',
    projectId: 'jadeais',
    authDomain: 'jadeais.firebaseapp.com',
    storageBucket: 'jadeais.appspot.com',
    measurementId: 'G-KY4QPW9K41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEx3gfKBXX4CMpx3wkD6T2_njx3HXoyM',
    appId: '1:897401434851:android:6c5f95d2563cb62c57cbd6',
    messagingSenderId: '897401434851',
    projectId: 'jadeais',
    storageBucket: 'jadeais.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cH_MUijvypThboOkaN055yTMCNKLoQA',
    appId: '1:897401434851:ios:1929e3cfdb531fd957cbd6',
    messagingSenderId: '897401434851',
    projectId: 'jadeais',
    storageBucket: 'jadeais.appspot.com',
    iosClientId: '897401434851-2lrggjfrbqodmhpoh6uh3me2hpiijlvg.apps.googleusercontent.com',
    iosBundleId: 'com.sifat.jadeais',
  );
}
